#### Recurrent Neural Network (RNN) :
-   Sequential Scenerios : where  input and output sequences are of same length. 
-   With RNN the feedback learning or the feedback loop works more efficiently . 
-   With each epoch running the model is constantly reciving feedbacks on the output layer. 

-   RNN is designed to handle sequential data more efficiently than ANN.
-   RNN processes input sequence of one element at a time.
-   RNN is more used into time series prediction.

In [2]:
pip install tensorflow


     ---------------------------------------- 0.0/57.5 kB ? eta -:--:--
     ---------------------------------------- 57.5/57.5 kB 1.5 MB/s eta 0:00:00
     ---------------------------------------- 0.0/65.5 kB ? eta -:--:--
     ---------------------------------------- 65.5/65.5 kB 1.8 MB/s eta 0:00:00
   ---------------------------------------- 0.0/377.1 MB ? eta -:--:--
   ---------------------------------------- 0.2/377.1 MB 7.4 MB/s eta 0:00:52
   ---------------------------------------- 0.3/377.1 MB 8.6 MB/s eta 0:00:44
   ---------------------------------------- 0.3/377.1 MB 8.6 MB/s eta 0:00:44
   ---------------------------------------- 0.3/377.1 MB 8.6 MB/s eta 0:00:44
   ---------------------------------------- 0.3/377.1 MB 8.6 MB/s eta 0:00:44
   ---------------------------------------- 0.3/377.1 MB 8.6 MB/s eta 0:00:44
   ---------------------------------------- 0.3/377.1 MB 8.6 MB/s eta 0:00:44
   ---------------------------------------- 0.3/377.1 MB 8.6 MB/s eta 0:00:44


  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.


   ---------------------------------------  376.0/377.1 MB 2.3 MB/s eta 0:00:01
   ---------------------------------------  376.0/377.1 MB 2.3 MB/s eta 0:00:01
   ---------------------------------------  376.1/377.1 MB 2.2 MB/s eta 0:00:01
   ---------------------------------------  376.2/377.1 MB 2.2 MB/s eta 0:00:01
   ---------------------------------------  376.2/377.1 MB 2.2 MB/s eta 0:00:01
   ---------------------------------------  376.3/377.1 MB 2.2 MB/s eta 0:00:01
   ---------------------------------------  376.4/377.1 MB 2.2 MB/s eta 0:00:01
   ---------------------------------------  376.5/377.1 MB 2.2 MB/s eta 0:00:01
   ---------------------------------------  376.6/377.1 MB 2.1 MB/s eta 0:00:01
   ---------------------------------------  376.7/377.1 MB 2.1 MB/s eta 0:00:01
   ---------------------------------------  376.8/377.1 MB 2.1 MB/s eta 0:00:01
   ---------------------------------------  377.0/377.1 MB 2.1 MB/s eta 0:00:01
   -------------------------------------

In [6]:
pip install distutils

Note: you may need to restart the kernel to use updated packages.


ERROR: Could not find a version that satisfies the requirement distutils (from versions: none)
ERROR: No matching distribution found for distutils


In [1]:
import numpy as np
import tensorflow as tf


In [2]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import SimpleRNN , Dense

In [3]:
np.random.seed(0)
xtrain=np.random.rand(100,10,1)
ytrain=np.random.rand(100,1)
xtest=np.random.rand(20,10,1)
ytest=np.random.rand(20,1)

In [4]:
xtrain

array([[[5.48813504e-01],
        [7.15189366e-01],
        [6.02763376e-01],
        [5.44883183e-01],
        [4.23654799e-01],
        [6.45894113e-01],
        [4.37587211e-01],
        [8.91773001e-01],
        [9.63662761e-01],
        [3.83441519e-01]],

       [[7.91725038e-01],
        [5.28894920e-01],
        [5.68044561e-01],
        [9.25596638e-01],
        [7.10360582e-02],
        [8.71292997e-02],
        [2.02183974e-02],
        [8.32619846e-01],
        [7.78156751e-01],
        [8.70012148e-01]],

       [[9.78618342e-01],
        [7.99158564e-01],
        [4.61479362e-01],
        [7.80529176e-01],
        [1.18274426e-01],
        [6.39921021e-01],
        [1.43353287e-01],
        [9.44668917e-01],
        [5.21848322e-01],
        [4.14661940e-01]],

       [[2.64555612e-01],
        [7.74233689e-01],
        [4.56150332e-01],
        [5.68433949e-01],
        [1.87898004e-02],
        [6.17635497e-01],
        [6.12095723e-01],
        [6.16933997e-01],
      

In [5]:
ytrain

array([[5.92880271e-01],
       [1.00636957e-02],
       [4.75826196e-01],
       [7.08770391e-01],
       [4.39754320e-02],
       [8.79521483e-01],
       [5.20081417e-01],
       [3.06610483e-02],
       [2.24413612e-01],
       [9.53675696e-01],
       [5.82319733e-01],
       [1.07472568e-01],
       [2.87544502e-01],
       [4.56703626e-01],
       [2.09500693e-02],
       [4.11615514e-01],
       [4.89458635e-01],
       [2.43677875e-01],
       [5.88639000e-01],
       [7.53240120e-01],
       [2.35834224e-01],
       [6.20499900e-01],
       [6.39622243e-01],
       [9.48540301e-01],
       [7.78276167e-01],
       [8.48345270e-01],
       [4.90419908e-01],
       [1.85348587e-01],
       [9.95815293e-01],
       [1.29355761e-01],
       [4.71457319e-01],
       [6.80930992e-02],
       [9.43850857e-01],
       [9.64924941e-01],
       [7.19389062e-01],
       [3.49992844e-01],
       [2.54382401e-01],
       [2.65303325e-01],
       [1.27294025e-01],
       [5.25808953e-01],


In [6]:
xtest

array([[[0.29594983],
        [0.92929167],
        [0.26590563],
        [0.82814661],
        [0.98510868],
        [0.78339665],
        [0.51898992],
        [0.06607426],
        [0.47241379],
        [0.43825595]],

       [[0.20279604],
        [0.42358764],
        [0.35775788],
        [0.16368426],
        [0.44137414],
        [0.26279996],
        [0.52206242],
        [0.03516006],
        [0.90623142],
        [0.81636431]],

       [[0.55258133],
        [0.85180858],
        [0.96239507],
        [0.11052229],
        [0.63083181],
        [0.997994  ],
        [0.98788917],
        [0.60332299],
        [0.12802087],
        [0.58319283]],

       [[0.00206464],
        [0.19891133],
        [0.95612316],
        [0.33044057],
        [0.63839011],
        [0.28085949],
        [0.94782189],
        [0.72855873],
        [0.32965116],
        [0.79176142]],

       [[0.10816552],
        [0.39231894],
        [0.22121813],
        [0.68372645],
        [0.10244628],
  

In [7]:
ytest

array([[0.86711454],
       [0.29426616],
       [0.43535347],
       [0.79545653],
       [0.67750836],
       [0.93786437],
       [0.62114033],
       [0.09781016],
       [0.88436036],
       [0.76915552],
       [0.71187045],
       [0.05373355],
       [0.39622274],
       [0.16743582],
       [0.82190391],
       [0.70052862],
       [0.8830776 ],
       [0.96657511],
       [0.77474761],
       [0.99423308]])

In [8]:
## Building the model
model=Sequential([
    SimpleRNN(64,input_shape=(10,1),activation='relu',return_sequences=False),Dense(1)
])

c:\Users\divya\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\rnn\rnn.py:205: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


In [9]:
model.compile(
    optimizer='adam',
    loss='mse',
    metrics=['mae']
)

-   MSE (Mean Squared Error) :  Squared up values of all the error , then finding the mean of all the squarred up errors. 
-   MAE (Mean Absolute Error) : The mean value of all errors in its absolute form . 

In [10]:
model.fit(xtrain,ytrain,epochs=10,batch_size=32,verbose=1)

Epoch 1/10
4/4 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.2429 - mae: 0.4172
Epoch 2/10
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.1796 - mae: 0.3491 
Epoch 3/10
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.1439 - mae: 0.3298 
Epoch 4/10
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.1267 - mae: 0.3078 
Epoch 5/10
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.1179 - mae: 0.2941 
Epoch 6/10
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.1303 - mae: 0.2858 
Epoch 7/10
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.1293 - mae: 0.2776 
Epoch 8/10
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.1216 - mae: 0.2912 
Epoch 9/10
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.1070 - mae: 0.2840 
Epoch 10/10
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.1060 - mae: 0.2779 


In [11]:
test_loss , test_mae=model.evaluate(xtest,ytest,verbose=1)
print('Test MAE',test_mae)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 191ms/step - loss: 0.1080 - mae: 0.2931
Test MAE 0.2931022346019745


In [14]:
xnew=np.random.rand(5,10,1) # 5 new sequence
prediction=model.predict(xnew)
print('Prediction for new data:')
print(prediction)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step
Prediction for new data:
[[0.31502753]
 [0.3453257 ]
 [0.6011932 ]
 [0.48741996]
 [0.34727728]]
